name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  job1-checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  job2-install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: job1-checkout
    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

  job3-build:
    name: Build Angular App
    runs-on: ubuntu-latest
    needs: job2-install-dependencies
    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Build Angular App
        run: ng build --configuration=production --base-href=https://jurfest.github.io/ia_pipeline_angular/

  job4-lint:
    name: Lint Angular App
    runs-on: ubuntu-latest
    needs: job3-build
    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Lint Angular App
        run: ng lint

  job5-test:
    name: Test Angular App
    runs-on: ubuntu-latest
    needs: job4-lint
    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Test Angular App
        run: ng test

  job6-deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: job5-test
    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist/ia-pipeline-angular

  job7-display-status:
    name: Display Job Status
    runs-on: ubuntu-latest
    needs: job6-deploy-gh-pages
    steps:
      - name: Display Job Status
        run: echo "The deployment job's status is ${{ job.status }}."
