name: GitHub Actions IA Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # At 03:35 on Saturday
    - cron: '35 3 * * 6'
  workflow_dispatch:

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
      - name: Display event information
        run: echo "The job was triggered by a ${{ github.event_name }} event."

      - name: Display runner information
        run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"

      - name: Display repository and branch information
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  checkout-repo:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Display repository clone message
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Display repository path
        run: echo "Your repository has been copied to the path ${{ github.workspace }} on the runner."

  setup-node:
    name: Setup Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: yarn

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn run build --configuration --prod --base-href=https://jurfest.github.io/ia_pipeline_angular/

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: yarn run test --single-run=true --progress=false

  display-version:
    name: Display Angular Version
    runs-on: ubuntu-latest
    steps:
      - name: Display Angular version
        run: yarn run ng version

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/ia-pipeline-angular
          enable_jekyll: true

  final-steps:
    name: Final Steps
    runs-on: ubuntu-latest
    steps:
      - name: Display job status
        run: echo "This job's status is ${{ job.status }}."
