name: GitHub Actions IA Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # At 03:35 on Saturday
    - cron: '35 3 * * 6'

  workflow_dispatch:

jobs:
  display-event-info:
    name: Display Event Information
    runs-on: ubuntu-latest
    steps:
      - name: Display event details
        run: |
          echo "The job was triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "Your repository has been copied to the path ${{ github.workspace }} on the runner."

  checkout-repo:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

  setup-node:
    name: Setup Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [checkout-repo, setup-node, install-dependencies]
    steps:
      - name: Build
        run: yarn build --prod --base-href=https://jurfest.github.io/ia_pipeline_angular/

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [checkout-repo, setup-node, install-dependencies]
    steps:
      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [checkout-repo, setup-node, install-dependencies]
    steps:
      - name: Test
        run: yarn test --single-run=true --progress=false

  display-version:
    name: Display Angular Version
    runs-on: ubuntu-latest
    needs: [checkout-repo, setup-node, install-dependencies]
    steps:
      - name: Display Angular version
        run: yarn ng version

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [checkout-repo, setup-node, install-dependencies, build]
    steps:
      - name: Deploy to GitHub Pages
        uses: angular-actions/github-pages-deploy@v0.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./dist/ia-pipeline-angular
          enable_jekyll: true

  display-job-status:
    name: Display Job Status
    runs-on: ubuntu-latest
    needs: [deploy-gh-pages]
    steps:
      - name: Display job status
        run: echo "This job's status is ${{ job.status }}."
