name: GitHub Actions IA Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # At 03:35 on Saturday
    - cron: '35 3 * * 6'

  workflow_dispatch:

jobs:
  checkout-setup:
    name: Checkout and Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display event details
        run: echo "The job was triggered by a ${{ github.event_name }} event."

      - name: Display runner information
        run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"

      - name: Display repository and branch details
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Display repository clone status
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."

  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: checkout-setup
    steps:
      - name: Setup Node on runner
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Nx CLI
        run: yarn global add nx

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Build
        run: yarn run build --configuration=production --base-href=https://jurfest.github.io/ia_pipeline_angular/

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test --single-run=true --progress=false

      - name: Display Angular version
        run: yarn run ng version

      - run: echo "The preinstalled tools are located here on the runner ${{ runner.tool_cache }}."

      - name: List files in tool cache
        run: |
          ls ${{ runner.tool_cache }}

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-lint-test
    steps:
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/ia-pipeline-angular
          enable_jekyll: true

      - name: Display job status
        run: echo "This job's status is ${{ job.status }}."
